src/movie_list/urls.py
from django.conf.urls import url
from movie_list.views import MovieCollection, MovieDetailView, MovieCreateView, MovieEditView, \
    FetchOMDBDataView, MovieDeleteView

urlpatterns = [
    url(r'^$', MovieCollection.as_view(), name='movie_list'),
    url(r'^(?P<pk>[0-9]+)/$', MovieDetailView.as_view(), name='movie_detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', MovieEditView.as_view(), name='edit_movie'),
    url(r'^(?P<pk>[0-9]+)/delete/$', MovieDeleteView.as_view(), name='delete_movie'),
    url(r'^add/$', MovieCreateView.as_view(), name='add_movie'),
    url(r'^fetch/$', FetchOMDBDataView.as_view(), name='fetch_movie'),
]

src/movies/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from movies.views import MainPage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainPage.as_view()),
    url(r'^movie_list/', include('movie_list.urls')),
    url('^users/', include('users.urls')),
]

src/users/urls.py
from django.conf.urls import url, include
from users.views import UserProfileView, UserEditProfileView, UserDeleteView, UserCreateView
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'users/logout.html', 'next_page': '/'}, name='logout'),
    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^profile/$', UserProfileView.as_view()),
    url(r'^profile/edit/$', UserEditProfileView.as_view()),
    url(r'^profile/delete/$', UserDeleteView.as_view()),
    url(r'^register/$', UserCreateView.as_view()),
]

src/movie_list/models.py
from django.db import models
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=20, default='')

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User)
    description = models.TextField(blank=True, max_length=300)
    metascore = models.IntegerField(blank=True, default=0)
    imdb_rating = models.FloatField(blank=True, default=0.0)
    imdb_url = models.URLField(blank=True, null=True)
    icon = models.URLField(blank=True, null=True)
    genre = models.ManyToManyField(Genre, blank=True)
    country = models.ManyToManyField(Country, blank=True)
    director = models.ManyToManyField(Person, blank=True, related_name='director')
    actors = models.ManyToManyField(Person, blank=True, related_name='actors')

    class Meta:
        unique_together = ('title', 'year', 'user')

    def __str__(self):
        return '{title} ({year})'.format(title=self.title, year=self.year)

src/movie_list/views.py
import urllib.parse

from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import resolve_url, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from movie_list.models import Movie, Genre
from omdb.service import OMDBFetcher
from omdb.fetcher import MovieNotFound
from movie_list.services import MovieService
from movie_list.mapping import LIST_VIEW_MAPPING


class MovieCollection(ListView):
    model = Movie
    template_name = 'movie_list/movie_list.html'

    def get_queryset(self):
        query = {
            LIST_VIEW_MAPPING[key]: value for key, value in self.request.GET.dict().items() if value
        }
        query['user'] = self.request.user
        queryset = super(MovieCollection, self).get_queryset()
        return queryset.filter(**query)

    def get_context_data(self, **kwargs):
        context = super(MovieCollection, self).get_context_data(**kwargs)
        context['genres'] = MovieService.get_genre_list()
        context['directors'] = MovieService.get_directors_list_for_user(self.request.user)
        context['actors'] = MovieService.get_actors_list_for_user(self.request.user)
        return context


class MovieDetailView(DetailView):
    template_name = 'movie_list/movie_detail.html'
    model = Movie

    def get_queryset(self):
        queryset = super(MovieDetailView, self).get_queryset()
        user = self.request.user
        return queryset.filter(user=user)


class MovieCreateView(CreateView):
    template_name = 'movie_list/add_movie.html'
    model = Movie
    fields = '__all__'

    def get(self, request, *args, **kwargs):
        super(MovieCreateView, self).get(request, *args, **kwargs)
        title = request.GET.get('title', '')
        year = request.GET.get('year', '')
        imdb_id = request.GET.get('imdb_id', '')
        form = request.GET.get('form', '')
        context = self.get_context_data()
        if (title and year) or imdb_id:
            try:
                selected_movie = OMDBFetcher().get(title=title, year=year, imdb_id=imdb_id)
            except MovieNotFound:
                context['alert'] = 'No movie was found for given parameters. Check the data or try filling form.'
            else:
                context['result'] = selected_movie
                if form:
                    context['movie'] = selected_movie[0]
        elif title:
            context['result'] = OMDBFetcher().page_search(title=title, page=1)
        else:
            context['result'] = []
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken', '')
        data['user'] = self.request.user
        MovieService().update_or_create(**data)
        return HttpResponseRedirect(resolve_url('movie_list'))


class FetchOMDBDataView(View):
    def post(self, request):
        title = request.POST.get('title', '')
        year = request.POST.get('year', '')
        imdb_id = request.POST.get('imdb_id', '')
        return self._redirect('add_movie', title=title, year=year, imdb_id=imdb_id)

    @staticmethod
    def _redirect(view, **kwargs):
        url = resolve_url(view)
        url += '?' + urllib.parse.urlencode(kwargs)
        return HttpResponseRedirect(url)


class MovieEditView(UpdateView):
    template_name = 'movie_list/edit_movie.html'
    model = Movie
    fields = '__all__'

    def get_queryset(self):
        queryset = super(MovieEditView, self).get_queryset()
        user = self.request.user
        return queryset.filter(user=user)

    def get_context_data(self, **kwargs):
        # Fixme: this is not a beauty, solution would be serialization
        context = {'movie': self.object.__dict__}
        context['movie']['genre'] = ', '.join(list(self.object.genre.all().values_list('name', flat=True)))
        context['movie']['actors'] = ', '.join(list(self.object.actors.all().values_list('name', flat=True)))
        context['movie']['director'] = ', '.join(list(self.object.director.all().values_list('name', flat=True)))
        context['movie']['country'] = ', '.join(list(self.object.country.all().values_list('name', flat=True)))
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken', '')
        data['user'] = self.request.user
        MovieService().update_or_create(**data)
        return HttpResponseRedirect(reverse_lazy('movie_detail', kwargs={'pk': self.object.pk}))


class MovieDeleteView(DeleteView):
    template_name = 'movie_list/delete_movie.html'
    success_url = reverse_lazy('movie_list')
    model = Movie

    def get_queryset(self):
        queryset = super(MovieDeleteView, self).get_queryset()
        user = self.request.user
        return queryset.filter(user=user)

src/movie_list/templates/movie_list/add_movie.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 col-sm-12">
    {% if alert %}
        <div class="alert alert-warning">
            <strong>Warning!</strong> {{alert}}
        </div>
    {% endif %}
    <h3 class="page-header">Try searching it in OMDB</h3>
    {% include 'movie_list/add_movie_search.html' %}
    <div>
        {% if result %}
            <h3>Search results:</h3>
        {% endif %}
        {% for movie in result %}
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="{{movie.icon}}" alt="...">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{movie.title}} <small>{{movie.year}}</small></h4>
                    <a href="{{movie.imdb_url}}">IMDB Page</a>
                </div>
                <div class="media-right">
                    <a class="btn btn-info" href="?title={{movie.title}}&year={{movie.year}}&form=true" role="button">
                        <span class="glyphicon glyphicon-ok"></span>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="col-md-6 col-sm-12">
    <h3 class="page-header">Or fill out the form below</h3>
    {% include 'movie_list/add_movie_form.html' %}
</div>
{% endblock %}

src/movie_list/templates/movie_list/add_movie_form.html
{% load custom_tag %}
<form class="form" action="" method="post">{% csrf_token %}
    <div class="form-group">
        <label>Title:</label>
        <input id="id_title" class="form-control" name="title" type="text" value="{{movie.title}}" required>
    </div>
    <div class="form-group">
        <label>Year:</label>
        <input id="id_year" class="form-control" name="year" type="number" min="1900" value="{{movie.year}}" required>
    </div>
    <div class="form-group">
        <label>Description:</label>
        <textarea
                id="id_description"
                class="form-control"
                rows="4"
                name="description"
        >{{movie.description}}</textarea>
    </div>
    <div class="form-group row">
        <div class="col-md-6">
            <label>IMDB Rating:</label>
            <input id="id_imdb_rating" class="form-control" min="0" max="10" step="0.1" name="imdb_rating" type="number" value="{{movie.imdb_rating}}">
        </div>
        <div class="col-md-6">
            <label>Metascore:</label>
            <input id="id_metascore" class="form-control" min="0" max="100" step="1" name="metascore" type="number" value="{{movie.metascore}}">
        </div>
    </div>
    <div class="form-group">
        <label>IMDB url:</label>
        <input id="id_imdb_url" class="form-control" name="imdb_url" type="url" value="{{movie.imdb_url}}">
        <label>Icon url:</label>
        <input id="id_icon" class="form-control" name="icon" type="url" value="{{movie.icon}}">
    </div>
    <div class="form-group">
        <label>Genre:</label>
        <input id="id_genre" class="form-control" name="genre" type="text" value="{{movie.genre}}">
        <label>Country:</label>
        <input id="id_country" class="form-control" name="country" type="text" value="{{movie.country}}">
        <label>Director:</label>
        <input id="id_director" class="form-control" name="director" type="text" value="{{movie.director}}">
        <label>Actors:</label>
        <input id="id_actors" class="form-control" name="actors" type="text" value="{{movie.actors}}">
    </div>
    <input class="btn btn-success btn-lg btn-block" type="submit" value="Submit" />
</form>

src/movie_list/templates/movie_list/add_movie_search.html
<form action="/movie_list/fetch/" method="post">{% csrf_token %}
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label>Title:</label>
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                    <input autofocus id="id_title" placeholder="The Room" class="form-control" name="title" type="text">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label>Year:</label>
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                    <input id="id_year" placeholder="2003" class="form-control" name="year" type="number" min="1900">
                </div>
            </div>
            <div class="col-md-6">
                <label>IMDB ID:</label>
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                    <input id="id_imdb_id" placeholder="tt0368226" class="form-control" name="imdb_id">
                </div>
            </div>
        </div>
    </div>
    <input class="btn btn-success btn-lg btn-block" type="submit" value="Search" />
</form>

src/movie_list/templates/movie_list/delete_movie.html
{% extends 'movie_list/movie_detail.html' %}
{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="alert alert-danger">
        <form class="form" method="post">{% csrf_token %}
            <div class="form-inline text-center">
                Are you sure you want to delete {{ object }}?
                <input type="submit" class="btn btn-danger" value="Confirm" />
            </div>
        </form>
    </div>
</div>
{{ block.super }}
{% endblock content %}

src/movie_list/templates/movie_list/edit_movie.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-8 col-md-offset-2">
    <h3 class="page-header">Edit movie:</h3>
    {% include 'movie_list/add_movie_form.html' %}
</div>
{% endblock content %}

src/movie_list/templates/movie_list/movie_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="page-header">
        <h1>{{movie.title}} <small>{{movie.year}}</small></h1>
    </div>
    <div class="col-sm-6">
        <img src="{{movie.icon}}" class="img-responsive" alt="Something went wrong :C">
    </div>
    <div class="col-sm-6">
        <div class="row">
            <strong>Plot:</strong>
            <em>{{movie.description}}</em>
        </div>
        <br>
        <div class="row">
            <table class="table">
                <tr>
                    <th>Genre(s):</th>
                    <td>{{ movie.genre.all|join:", " }}</td>
                </tr>
                <tr>
                    <th>Country:</th>
                    <td>{{ movie.country.all|join:", " }}</td>
                </tr>
                <tr>
                    <th>Director(s):</th>
                    <td>{{ movie.director.all|join:", " }}</td>
                </tr>
                <tr>
                    <th>Actor(s):</th>
                    <td>{{ movie.actors.all|join:", " }}</td>
                </tr>
            </table>
        </div>
        <div class="row">
            <ul class="list-inline list-unstyled pull-right">
                <li>
                    <img src="http://findicons.com/files/icons/2229/social_media_mini/32/imdb.png" alt="" title="imdb">
                    {{movie.imdb_rating|default:"-"}}
                </li>
                <li>
                    <img src="http://icons.veryicon.com/32/Internet%20%26%20Web/Social%20Bookmark/Metacritic.png" alt="" title="metacritic">
                    {{movie.metascore|default:"-"}}%
                </li>
            </ul>
        </div>
        <br>
        <div class="row">
            <a class="btn btn-info btn-lg btn-block" href="/movie_list/{{movie.pk}}/edit/" role="button">
                <span class="glyphicon glyphicon-pencil"></span>
                Edit info
            </a>
            <a class="btn btn-danger btn-lg btn-block" href="/movie_list/{{movie.pk}}/delete/" role="button">
                <span class="glyphicon glyphicon-remove"></span>
                Delete movie
            </a>
        </div>
    </div>
</div>
{% endblock %}

src/movie_list/templates/movie_list/movie_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="page-header">Movie Collection
        <div class="pull-right">
            <button class="btn btn-info" type="button" data-toggle="collapse"
                    data-target="#filters" aria-expanded="false" aria-controls="filters">
                Filters
            </button>
        </div>
    </h1>
    <div id="filters" class="collapse container-fluid">
        <form class="form-horizontal" action="" method="get">
            <div class="form-group form-group-sm col-md-4">
                <label for="id_title" class="control-label">Title:</label>
                <input id="id_title" class="form-control input-sm" name="title" type="text">
                <div class="row">
                    <div class="col-md-6">
                        <label for="id_year_from" class="control-label">From year:</label>
                        <input id="id_year_from" class="form-control input-sm"
                               name="year_from" min="1900" placeholder="2000" type="number">
                    </div>
                    <div class="col-md-6">
                        <label for="id_year_to" class="control-label">To:</label>
                        <input id="id_year_to" class="form-control input-sm"
                               name="year_to" min="1900" placeholder="2016" type="number">
                    </div>
                </div>
            </div>
            <div class="form-group form-group-sm col-md-4">
                <div class="col-md-12">
                    <label for="id_actors" class="control-label">Actors:</label>
                    <select id="id_actors" class="form-control input-sm" name="actors">
                        <option></option>
                        {% for type in actors %}
                            <option>{{type}}</option>
                        {% endfor %}
                    </select>
                    <label for="id_director" class="control-label">Director:</label>
                    <select id="id_director" class="form-control input-sm" name="director">
                        <option></option>
                        {% for type in directors %}
                            <option>{{type}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group form-group-sm col-md-4">
                <div class="col-md-12">
                    <label for="id_genre" class="control-label">Genre:</label>
                    <select id="id_genre" class="form-control input-sm" name="genre">
                        <option></option>
                        {% for type in genres %}
                            <option>{{type}}</option>
                        {% endfor %}
                    </select>
                    <input class="pull-right btn btn-success btn-sm btn-block"
                           style="margin-top:24px;" type="submit" value="Search" />
                </div>
            </div>
        </form>
    </div>
    <div>
        {% with object_list|length as total %}
            <h4 class="page-header">{{total}} movie{{ total|pluralize }} found.</h4>
        {% endwith %}
    </div>
    {% for movie in object_list|dictsort:"year" %}
        <div class="col-xs-12 col-md-4">
            <div class="thumbnail">
                <img src="{{movie.icon}}" alt="Something went wrong :C" height="150">
                <div class="caption">
                    <h3>{{movie.title}} <small>{{movie.year}}</small></h3>
                    <p>{{movie.description|truncatewords:15}}</p>
                    <a class="btn btn-info btn-lg btn-block" href="/movie_list/{{movie.pk}}/" role="button">
                        More info..
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
     <div class="navbar-fixed-bottom col-md-offset-11">
        <a
                id="back-to-top"
                href="#"
                class="btn btn-info btn-lg back-to-top"
                role="button"
                data-placement="right">
            <span class="glyphicon glyphicon-chevron-up"></span>
        </a>
    </div>
{% endblock %}